<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SsoCore.Infrastructure</AssemblyName>
    <RootNamespace>SsoCore.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.3.6" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.2" />
    <PackageReference Include="OpenIddict.Client.WebIntegration" Version="6.1.1" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="6.1.1" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore.Models" Version="6.1.1" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0-preview.3.efcore.9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SsoCore.Application\SsoCore.Application.csproj" />
  </ItemGroup>

</Project>
